version: 2
jobs:
  build:
    docker:
      - image: vvakame/review
    steps:
      - checkout
      - run:
          name: Build PDF
          command: review-pdfmaker config.yml
          working_directory: ./articles
      - store_artifacts:
          path: ./articles/book.pdf
          destination: book.pdf