version: 2
jobs:
  build:
    docker:
      - image: vvakame/review
    steps:
      - checkout
      - run:
          name: show dest
          command: ls
          working_directory: ./
      - run:
          name: Build PDF
          command: review-pdfmaker config.yml
          working_directory: ./
      - run:
          name: show dest
          command: ls
          working_directory: ./
      - store_artifacts:
          path: ./book.pdf
          destination: output.pdf